name: Velcro
description: Intuitive network reverse-engineering toolkit for FFXIV.
domain: velcro-xiv.github.io
url: https://velcro-xiv.github.io
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
